name: 🐛 Report a bug
description: Submit a bug report to help us enhance swurg.
title: "[BUG] <title>"
labels: [bug]
assignees: aress31
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: "Prior to submitting the issue, ensure that you have:"
      options:
        - label: Thoroughly read the [README file](https://github.com/aress31/swurg/blob/main/README.md).
          required: true
        - label: Checked the [project requirements](https://github.com/aress31/swurg#requirements) and ensured they are met.
          required: true
        - label: Searched for existing issues that may address the problem.
          required: true
        - label: Performed basic troubleshooting steps.
          required: true
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error...
      description: Steps to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      value: |
        - OS: [e.g. Windows, macOS, Linux]
        - Java version: [e.g. 8, 11, 16, 17]
        - Burp Suite version: [e.g. Professional 2023.12, Community 2023.12]
        - OpenAPI Specification version: [e.g., 1.0, 2.0, 3.0]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Error Message
      description: |
        1. Navigate to the `Dashboard` -> `Event Log` to see if there are any relevant error messages available.
        2. Additionally, go to `Extensions` -> `Installed` -> `Swurg`, and check the `Output` and `Error` tabs for any error messages.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false
