name: 🚀 Report a feature request
description: Submit a proposal for an idea or enhancement to swurg.
title: "[FEATURE] <title>"
labels: [enhancement]
assignees: aress31
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: "Prior to submitting the issue, ensure that you have:"
      options:
        - label: Searched for existing feature requests that may address the problem.
          required: true
  - type: textarea
    attributes:
      label: Problem or Use Case
      description: A clear and concise description of the problem or use case where swurg would be useful.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Solution
      description: A clear and concise description of what you want to happen. Please provide as much detail as possible, including how the feature would interact with swurg and Burp Suite.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternative Solutions Considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Example
      description: If applicable, provide an example of how the feature would work.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Add any other context, screenshots, or references about the feature request here.
    validations:
      required: true
